const WebSocket = require('ws');
const fs = require('fs');
const path = require('path');

const port = 9001;

const wss = new WebSocket.Server({ port: port });


function get_dir(_path) {
	return path.join(require.main.filename, '../../../../my/', `/page/${_path}`)
}

function write(_path, data) {
	fs.writeFileSync(get_dir(_path), data, 'utf-8')
}


wss.on('connection', function connection(ws) {
	ws.on('message', function incoming(message) {
		const parsed = JSON.parse(message);

		if (parsed.tree) {
			let module = parsed.tree.trim().substr(0, parsed.tree.trim().indexOf(' '));
			let module_name = module.substr(module.lastIndexOf('_') + 1);
			if (module.indexOf('my_page') == -1) {
				module_name = parsed.user;
				const module_new = `$my_page_${parsed.user}_${module_name}`;
				parsed.tree = parsed.tree.replace(module, module_new);
			}
			parsed.tree = parsed.tree.replace(module, `$my_page_${parsed.user}_${module_name}`);
			if (parsed.css) {
				var find = module.replace('$', '');
				var re = new RegExp(find, 'g');
				parsed.css = parsed.css.replace(re, `my_page_${parsed.user}_${module_name}`)
			}
			if (parsed.ts) {
				parsed.ts = parsed.ts.replace(module, `$my_page_${parsed.user}_${module_name}`)
			}

			if (!parsed.ts) {
				parsed.ts = ''
			}
			if (!parsed.css) {
				parsed.css = '';
			}
			if (!parsed.meta) {
				parsed.meta = '';
			}
			if (!fs.existsSync(get_dir(`${parsed.user}/${module_name}`))) {
				fs.mkdirSync(get_dir(`${parsed.user}/${module_name}`), {
					recursive: true
				});
			}
			write(`${module_name}.view.tree`, parsed.tree);
			write(`${module_name}.view.ts`, parsed.ts);
			write(`${module_name}.view.css`, parsed.css);
			write(`${module_name}.meta.tree`, parsed.meta);
			write(`index.html`, getTemplate(new Date().getTime(), `$my_page_${parsed.user}_${module_name}`));
			const execSync = require('child_process').execSync

			// if (!fs.existsSync(get_dir(`${parsed.user}/${module_name}/-`))) {
			// 	let output = execSync(`cd ${path.join(__dirname, '../../../')} && yarn start my/page`);
			// }
			setTimeout(() => {
				execSync(`cd ${path.join(__dirname, '../../../my/page/')} && cp -R '-' ${parsed.user}/${module_name}/`);
				ws.send(JSON.stringify({ ...parsed, module: `page/${parsed.user}/${module_name}` }));
			}, 5000);

		}

	});

});


const getTemplate = (time, module_name) => {
	return `
	
	<!-- Disable quirks mode -->
<!DOCTYPE html>
<!-- Allow height:100% in body -->
<html style=" height: 100% ">
	<!-- Force utf-8 encoding -->
	<meta charset="utf-8" />
	<!-- Disable mobile browser auto zoom, $mol is adaptive -->
	<meta
		name="viewport"
		content="width=device-width, height=device-height, initial-scale=1"
	/>
	<!-- link to autogenerated js bundle -->
	<script src="web.js"></script>
	
	<!-- autobind component to element on load -->
	<body mol_view_root="${module_name}"></body>
</html>
	
	`
}
